server:
  port: 8888

spring:
  application:
    name: configserver
    bus:
      trace:
        enable: true  #SpringCloud Bus，能实现无需重启，自动感知配置变化以及应用新配置；

# spring-cloud配置中心两种配置方式
#        1、从git读取各个微服务的配置文件
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhencym/OrderingSystem.git #git仓库地址
          searchPaths: config #仓库路径
          username: zhencym #git仓库用户名
          password: qq1540504013 #git仓库密码
        label: master #仓库的分支

#        2、从本地读取各个微服务的配置文件
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/config

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true